### PR TITLE
Fix build for sqrt usage in vector.

### PR DESCRIPTION
**Pull request by asluk**
Adding cmath include to fix OSX build (issue #83).

### CODE REVIEW

**Comment by ondys** [comment]
Thanks for catching and fixing this

**Comment by jwakely** [comment]
Since `sqrt` is called unqualified you need to include `<math.h>` not `<cmath>`. Either that or add a using-declaration. There's no guarantee that `<cmath>` declares `sqrt` in the global namespace.

**Comment by ondys** [comment]
@jwakely In our internal version, we have already changed this to std::sqrt which I believe requires <cmath>

**Comment by jwakely** [comment]
@ondys right, if you use `std::sqrt` you should include `<cmath>` and if you use `::sqrt` you should include `<math.h>` so sounds like it's correct now. Jolly good!

**Pull request merged**
