### PR TITLE
Fixed hundreds compiler warnings #411

### PR DESCRIPTION
**Pull request by FreddyFunk**
The whole draco project compiled in debug mode with **over 900 compiler warings** in Visual Studio before due to inappropriate casts in most cases. Mosts of them are fixed with this pull request. Now there are only around 120 compiler warnings left.

### CODE REVIEW

**Comment by tomfinegan** [comment]
@FreddyFunk: Thanks for the PR. I'm really sorry to point this out, but we can't accept this PR as-is. Our coding style guidelines[1] forbid the use of c-style casts. 

If you modify the PR to use C++ style casts I can accept it.

Note that you'll have to sign the CLA as well.

[1] https://google.github.io/styleguide/cppguide.html#Casting

**Comment by FreddyFunk** [comment]
Thanks for your fast answer. I will look into the CLA and rework PR for C++ style casts.

**Comment by FreddyFunk** [comment]
I signed the CLA.

**Comment by tomfinegan** [comment]
@FreddyFunk 

Thanks for updating this PR, and sorry for the latency. I'll try to get this merged in next week. I've been on break (along with some other members of the team), which has been getting in the way.

**Pull request merged**
