### PR TITLE
[cmake] Re-fix the cmake config files

### PR DESCRIPTION
**Pull request by JackBoosY**
Continue PR https://github.com/google/draco/pull/775.
1. Use cmake function `EXPORT` instead of hardcode.
2. `DRACO_LIB_DIR` -> `DRACO_LIBRARY_DIR` (See https://github.com/google/draco/pull/775 comment).
3. Add cmake vairable `DRACO_FOUND`.

### CODE REVIEW

**Comment by JackBoosY** [comment]
CLA signed.

**Comment by JackBoosY** [comment]
Any news here?

**Comment by JackBoosY** [comment]
> Not yet, perhaps later in the week-- vcpkg support is not a project priority.

Yeah vcpkg is not high pirority, but this is a bug.

**Comment by tomfinegan** [comment]
Closing this in favor of the changes in #796. At present I don't see a really good reason for using the export functionality to achieve what the addition of a find_library() call to the config file can handle. Please open a new issue if problems persist after the latest update to the CMake config file.

**Pull request closed without merging**
